### ISSUE TITLE
White Background while in Settings

### ISSUE THREAD

**Issue by EliaPym** [adesurirey/typora-notes-dark-theme#13]
I've only just recently downloaded the 'Notes Dark' Theme for Typora, however have noticed an issue that doesnt occur with other dark theme UIs.

Basically while in the settings menu the background (as well as text) is white. This means you cannot read anything on the screen. Its fine while in the text editor but just not in the menu.

https://imgur.com/a/76kzM6H

**Comment by Semt3x** [comment]
Hello,

It's not only a Linux bug, I also have the same result on Windows

**Comment by adesurirey** [comment]
Thank you for reporting @SpackWasTaken @Semt3x, but I don't have any Linux or Windows laptop to test the theme on. 

Could you investigate a bit more on this? 

You can enable debugging in the help menu on Typora and inspect the app like you would in a browser. Try inspecting the settings HTML and find the CSS rule that is wrong. You can post some screenshots here or open a PR if you find the solution to it. I'll be happy to merge it.

**Comment by adesurirey** [comment]
A user just found out that the theme name is the origin of a similar issue we have on macOS: https://github.com/typora/typora-issues/issues/3776#issuecomment-723086716

Could you please try changing the theme name from `notes-dark.css` to `notesdark.css` and report if the issue persist ?

**Comment by Semt3x** [comment]
Hello, 

For me, it didn't seem to do the trick : 
![image](https://user-images.githubusercontent.com/1705055/98518388-a03d0580-226f-11eb-98c1-f0436e4116ba.png)

![image](https://user-images.githubusercontent.com/1705055/98518333-87cceb00-226f-11eb-8c06-86b3520e4beb.png)

I restarted Typora to ensure this wasn't that.
I'll have a look at the debugger when I get the occasion.

**Comment by orchetect** [comment]
If I recall, this was actually a Typora bug that was fixed. Are you still having this issue?

**Comment by Askaniy** [comment]
I have the same problem on Windows with the latest versions (installed yesterday)

**Comment by adesurirey** [comment]
@Askaniy https://github.com/adesurirey/typora-notes-dark-theme/issues/13#issuecomment-721870608

**Comment by Askaniy** [comment]
Sorry, I have no experience with html. Looking at the CSS, I can only say that the background color on the menu screen is in a white cube pattern instead of `--bg-color`.
![image](https://user-images.githubusercontent.com/44873271/109338633-90c1e680-7877-11eb-83f1-0f7cb501eca5.png)

**Comment by adesurirey** [comment]
Looking at other themes, I thing we should experiment those selectors.
 
```
#megamenu-content
.ty-preferences
```
