### ISSUE TITLE
关于标题的建议

### ISSUE THREAD

**Issue by suyinLoong** [adesurirey/typora-notes-dark-theme#16]
期望出现的结果(Desired results)
![1](https://user-images.githubusercontent.com/49554285/110232552-4c120b80-7f59-11eb-82e7-e47aee798e87.png)
实际出现的结果(The actual results)
![2](https://user-images.githubusercontent.com/49554285/110232557-52a08300-7f59-11eb-8f7c-3904682876e6.png)
希望可以在各级标题前显示标题是几级标题，谢谢！(I hope that the title can be displayed in front of the title of each level, thank you!)

**Comment by adesurirey** [comment]
Could you provide an english version of your issue?

**Comment by adesurirey** [comment]
Closing as it looks like the last Typora release fixed this

![image](https://user-images.githubusercontent.com/22000544/122785035-4dbad180-d2b3-11eb-928c-96b8d5c89622.png)

![image](https://user-images.githubusercontent.com/22000544/122785011-472c5a00-d2b3-11eb-8696-bf4ea4a81fdf.png)
