### ISSUE TITLE
set image left-aligned

### ISSUE THREAD

**Issue by hjd6633** [adesurirey/typora-notes-dark-theme#19]
Hi, thanks for developing this theme, it's my favourite.   
I'd like to set my images left aligned.  Tried hard as i can,  i still can't find a solution for Notes Dark theme.  Could you please shed lignt on the subject?   

The codes on typora  https://support.typora.io/Images/ doesn't solve my thing.   

Thank you very much.

**Comment by adesurirey** [comment]
Hi @hjd6633 and thank you for your support. 

This is a Typora issue, from your link: 
> Currently Typora does not support image alignment. [...] Also, by default, if a paragraph only contains one image, it will be center aligned.

And there's already an open issue: https://github.com/typora/typora-issues/issues/2242

Notes Dark is just a theme and we don't aim at adding features or going around Typora defaults.

**Comment by hjd6633** [comment]
Thank you for your reply.  Hopefully Typora can offer a hack in her next version. 
Thank you again for this lovely theme.
