### ISSUE TITLE
A Light Theme

### ISSUE THREAD

**Issue by KaiHuaDou** [adesurirey/typora-notes-dark-theme#20]
I'm loving this dark theme and it is my default dark theme. 
I hope there will also be a `Note Light` theme. 
Thank You.

**Comment by adesurirey** [comment]
Thank you @KaiHuaDou!

I'm not using Typora anymore so I won't be developing it myself,  but I would be happy to help anyone doing it.

**Comment by KaiHuaDou** [comment]
Thank you very much!
