### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by atraest** [adesurirey/typora-notes-dark-theme#4]
Hello. Beautiful theme! What's the license?

**Comment by adesurirey** [comment]
Thank you! I just added an MIT licence https://github.com/adesurirey/typora-notes-dark-theme/commit/ee70277e5f265123dd1d6fc95d1824a82f0f92ea

**Comment by atraest** [comment]
Hey @adesurirey I've made a Horizon theme based on your stunning theme! Proper credits and license, please let me know if I forgot something or if you need something changed.

I took the liberty of including a _Dropdown_ menu theme based on [Ursine](https://github.com/aCluelessDanny/typora-theme-ursine) right before the **#Writes**.

[Typora Horizon Theme](https://github.com/estatra/typora-horizon-theme)
