### ISSUE TITLE
Document Window Flashes White When First Opening

### ISSUE THREAD

**Issue by orchetect** [adesurirey/typora-notes-dark-theme#5]
On macOS 10.15.5 with system-wide Dark Mode on and using Notes Dark Theme in Typora, whenever a new document is created or a markdown file is opened, the entire window flashes white for half a second, then goes dark.

There must be a theme/css flag you can set to fix this, as I haven't seen it happen on other dark Typora themes.

**Comment by adesurirey** [comment]
Thank you for reporting.

I have the same issue when first opening but not when creating new files or opening it.

I tested most of the other dark themes and the majority of it has the same issue: 
- Onedark
- Ursine Umbra
- Quartz Smoky
- Vue Dark

Only 2 themes I tested doesn't have it: 
- Xydark
- Night

At the moment I don't see any css variable I could set or rule that could fix it. 

Things I tried based on the working themes: 
- Setting `background` and `background-color` on the `body` and/or `html` tags, and marking it as `!important`.
- Setting `--node-fill` variable (I don't know what it's supposed to be, but Onedark does it).

Any help is welcome.

**Comment by adesurirey** [comment]
> whenever a new document is created or a markdown file is opened, the entire window flashes white for half a second, then goes dark.

I only have this issue when first opening Typora, not when opening or creating files. 

**Typora:** Version 0.9.9.34.2 
**Notes Dark:** v1.6

Can you please download the latest release of both Typora and Notes Dark, and report if you still have the issue on opening and creating?

**Comment by orchetect** [comment]
> **Typora:** Version 0.9.9.34.2
> **Notes Dark:** v1.6
> 
> Can you please download the latest release of both Typora and Notes Dark, and report if you still have the issue on opening and creating?

Yes, I'm on the latest Typora (that version #) and have the most recent Notes Dark theme.

The white flash happens on multiple different Macs of mine, all with different versions of macOS: 10.14.6, 10.15.5, 10.15.6.

The issue happens regardless whether macOS is set to Light Mode or Dark Mode.

I tried hacking around modifying the theme to see if I could narrow down the culprit and I came up dry. Like you said, the "Night" Typora theme works fine without this issue. I dissected it and compared it against Notes Dark and after a fair amount of alterations, I could not figure out why Night is fine and why Notes Dark is not.

Could it be an issue with Typora somehow? I wonder if it's worth reaching out to the dev team perhaps.

**Comment by adesurirey** [comment]
To recap, I see 2 issues: 

<details>
 <summary>White flash at startup</summary>

![notes-dark-startup](https://user-images.githubusercontent.com/22000544/89983445-db7f6680-dc77-11ea-8b04-9c6a44a0ec80.gif)
</details>

<details>
 <summary>White / Yellow flash when creating new documents</summary>

![notes-dark-new-note](https://user-images.githubusercontent.com/22000544/89983826-a1fb2b00-dc78-11ea-97ef-15a7bca11ab1.gif)
</details>

I opened an issue on Typora issues and an other on Ursine Umbra which has the same issue and is a well maintained theme: https://github.com/aCluelessDanny/typora-theme-ursine/issues/63

**Comment by noatpad** [comment]
This was something I always took as normal behavior, but I wasn't aware that some themes like Xydark or Night didn't have this flash. I might give their themes a look to see if I can find anything.

Also, you mentioned _white/yellow flash when creating new documents_ as an issue you have. Ursine used to have this problem, but I fixed that by basically disabling the built-in animation Typora uses when creating or updating filenames:

```css
.blink-area { animation: none; }
```

**Comment by adesurirey** [comment]
That's one problem solved, thank you for your help @aCluelessDanny!

**Comment by adesurirey** [comment]
Fixed in Typora Version 0.9.9.36.2 (4901)
